Python 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
from nltk.tokenize import word_tokenize
s="For timekeeping, Finland follows Eastern European Time (EET) during its winter as standard time and Eastern European Summer Time (EEST) in the summer as daylight saving time. EET is two hours ahead of Coordinated Universal Time and EEST is three hours ahead. Finland adopted EET in 1921, and daylight saving time in its current form from 1981. Up to the 19th century, each locality used its own solar time, which could vary in Finland by up to 31 minutes. In 1862, a mean time was adopted as a single time zone for railway scheduling. Daylight saving time was first attempted in 1942, abandoned as not useful, and introduced again in 1981 to align with neighbouring countries. In 2017, the Finnish parliament voted to call on the European Union to abolish daylight saving time. Finland's time zone is maintained by the VTT Technical Research Centre of Finland and the Centre for Metrology and Accreditation, using an atomic clock and hydrogen monitors. The 24-hour clock notation is used in Finland."
s
"For timekeeping, Finland follows Eastern European Time (EET) during its winter as standard time and Eastern European Summer Time (EEST) in the summer as daylight saving time. EET is two hours ahead of Coordinated Universal Time and EEST is three hours ahead. Finland adopted EET in 1921, and daylight saving time in its current form from 1981. Up to the 19th century, each locality used its own solar time, which could vary in Finland by up to 31 minutes. In 1862, a mean time was adopted as a single time zone for railway scheduling. Daylight saving time was first attempted in 1942, abandoned as not useful, and introduced again in 1981 to align with neighbouring countries. In 2017, the Finnish parliament voted to call on the European Union to abolish daylight saving time. Finland's time zone is maintained by the VTT Technical Research Centre of Finland and the Centre for Metrology and Accreditation, using an atomic clock and hydrogen monitors. The 24-hour clock notation is used in Finland."
s_words=word_tokenize(s)
s_words
['For', 'timekeeping', ',', 'Finland', 'follows', 'Eastern', 'European', 'Time', '(', 'EET', ')', 'during', 'its', 'winter', 'as', 'standard', 'time', 'and', 'Eastern', 'European', 'Summer', 'Time', '(', 'EEST', ')', 'in', 'the', 'summer', 'as', 'daylight', 'saving', 'time', '.', 'EET', 'is', 'two', 'hours', 'ahead', 'of', 'Coordinated', 'Universal', 'Time', 'and', 'EEST', 'is', 'three', 'hours', 'ahead', '.', 'Finland', 'adopted', 'EET', 'in', '1921', ',', 'and', 'daylight', 'saving', 'time', 'in', 'its', 'current', 'form', 'from', '1981', '.', 'Up', 'to', 'the', '19th', 'century', ',', 'each', 'locality', 'used', 'its', 'own', 'solar', 'time', ',', 'which', 'could', 'vary', 'in', 'Finland', 'by', 'up', 'to', '31', 'minutes', '.', 'In', '1862', ',', 'a', 'mean', 'time', 'was', 'adopted', 'as', 'a', 'single', 'time', 'zone', 'for', 'railway', 'scheduling', '.', 'Daylight', 'saving', 'time', 'was', 'first', 'attempted', 'in', '1942', ',', 'abandoned', 'as', 'not', 'useful', ',', 'and', 'introduced', 'again', 'in', '1981', 'to', 'align', 'with', 'neighbouring', 'countries', '.', 'In', '2017', ',', 'the', 'Finnish', 'parliament', 'voted', 'to', 'call', 'on', 'the', 'European', 'Union', 'to', 'abolish', 'daylight', 'saving', 'time', '.', 'Finland', "'s", 'time', 'zone', 'is', 'maintained', 'by', 'the', 'VTT', 'Technical', 'Research', 'Centre', 'of', 'Finland', 'and', 'the', 'Centre', 'for', 'Metrology', 'and', 'Accreditation', ',', 'using', 'an', 'atomic', 'clock', 'and', 'hydrogen', 'monitors', '.', 'The', '24-hour', 'clock', 'notation', 'is', 'used', 'in', 'Finland', '.']
tags=nltk.pos_tag(s_words)
Traceback (most recent call last):
  File "<pyshell#5>", line 1, in <module>
    tags=nltk.pos_tag(s_words)
NameError: name 'nltk' is not defined
import nltk
tags=nltk.pos_tag(s_words)
tags
[('For', 'IN'), ('timekeeping', 'VBG'), (',', ','), ('Finland', 'NNP'), ('follows', 'VBZ'), ('Eastern', 'JJ'), ('European', 'JJ'), ('Time', 'NNP'), ('(', '('), ('EET', 'NNP'), (')', ')'), ('during', 'IN'), ('its', 'PRP$'), ('winter', 'NN'), ('as', 'IN'), ('standard', 'JJ'), ('time', 'NN'), ('and', 'CC'), ('Eastern', 'JJ'), ('European', 'JJ'), ('Summer', 'NN'), ('Time', 'NNP'), ('(', '('), ('EEST', 'NNP'), (')', ')'), ('in', 'IN'), ('the', 'DT'), ('summer', 'NN'), ('as', 'IN'), ('daylight', 'NN'), ('saving', 'VBG'), ('time', 'NN'), ('.', '.'), ('EET', 'NNP'), ('is', 'VBZ'), ('two', 'CD'), ('hours', 'NNS'), ('ahead', 'RB'), ('of', 'IN'), ('Coordinated', 'NNP'), ('Universal', 'NNP'), ('Time', 'NNP'), ('and', 'CC'), ('EEST', 'NNP'), ('is', 'VBZ'), ('three', 'CD'), ('hours', 'NNS'), ('ahead', 'RB'), ('.', '.'), ('Finland', 'NNP'), ('adopted', 'VBD'), ('EET', 'NNP'), ('in', 'IN'), ('1921', 'CD'), (',', ','), ('and', 'CC'), ('daylight', 'VBD'), ('saving', 'VBG'), ('time', 'NN'), ('in', 'IN'), ('its', 'PRP$'), ('current', 'JJ'), ('form', 'NN'), ('from', 'IN'), ('1981', 'CD'), ('.', '.'), ('Up', 'IN'), ('to', 'TO'), ('the', 'DT'), ('19th', 'JJ'), ('century', 'NN'), (',', ','), ('each', 'DT'), ('locality', 'NN'), ('used', 'VBN'), ('its', 'PRP$'), ('own', 'JJ'), ('solar', 'JJ'), ('time', 'NN'), (',', ','), ('which', 'WDT'), ('could', 'MD'), ('vary', 'VB'), ('in', 'IN'), ('Finland', 'NNP'), ('by', 'IN'), ('up', 'IN'), ('to', 'TO'), ('31', 'CD'), ('minutes', 'NNS'), ('.', '.'), ('In', 'IN'), ('1862', 'CD'), (',', ','), ('a', 'DT'), ('mean', 'JJ'), ('time', 'NN'), ('was', 'VBD'), ('adopted', 'VBN'), ('as', 'IN'), ('a', 'DT'), ('single', 'JJ'), ('time', 'NN'), ('zone', 'NN'), ('for', 'IN'), ('railway', 'NN'), ('scheduling', 'NN'), ('.', '.'), ('Daylight', 'NNP'), ('saving', 'VBG'), ('time', 'NN'), ('was', 'VBD'), ('first', 'RB'), ('attempted', 'VBN'), ('in', 'IN'), ('1942', 'CD'), (',', ','), ('abandoned', 'VBD'), ('as', 'IN'), ('not', 'RB'), ('useful', 'JJ'), (',', ','), ('and', 'CC'), ('introduced', 'VBD'), ('again', 'RB'), ('in', 'IN'), ('1981', 'CD'), ('to', 'TO'), ('align', 'VB'), ('with', 'IN'), ('neighbouring', 'JJ'), ('countries', 'NNS'), ('.', '.'), ('In', 'IN'), ('2017', 'CD'), (',', ','), ('the', 'DT'), ('Finnish', 'NNP'), ('parliament', 'NN'), ('voted', 'VBD'), ('to', 'TO'), ('call', 'VB'), ('on', 'IN'), ('the', 'DT'), ('European', 'NNP'), ('Union', 'NNP'), ('to', 'TO'), ('abolish', 'VB'), ('daylight', 'NN'), ('saving', 'VBG'), ('time', 'NN'), ('.', '.'), ('Finland', 'NNP'), ("'s", 'POS'), ('time', 'NN'), ('zone', 'NN'), ('is', 'VBZ'), ('maintained', 'VBN'), ('by', 'IN'), ('the', 'DT'), ('VTT', 'NNP'), ('Technical', 'NNP'), ('Research', 'NNP'), ('Centre', 'NNP'), ('of', 'IN'), ('Finland', 'NNP'), ('and', 'CC'), ('the', 'DT'), ('Centre', 'NNP'), ('for', 'IN'), ('Metrology', 'NNP'), ('and', 'CC'), ('Accreditation', 'NNP'), (',', ','), ('using', 'VBG'), ('an', 'DT'), ('atomic', 'JJ'), ('clock', 'NN'), ('and', 'CC'), ('hydrogen', 'NN'), ('monitors', 'NNS'), ('.', '.'), ('The', 'DT'), ('24-hour', 'JJ'), ('clock', 'NN'), ('notation', 'NN'), ('is', 'VBZ'), ('used', 'VBN'), ('in', 'IN'), ('Finland', 'NNP'), ('.', '.')]
tree=nltk.ne_chunk(tags)
tree.draw()
for i in nltk.ne_chunk(tags):
    print(i)

('For', 'IN')
('timekeeping', 'VBG')
(',', ',')
(GPE Finland/NNP)
('follows', 'VBZ')
(GPE Eastern/JJ)
(LOCATION European/JJ Time/NNP)
('(', '(')
(ORGANIZATION EET/NNP)
(')', ')')
('during', 'IN')
('its', 'PRP$')
('winter', 'NN')
('as', 'IN')
('standard', 'JJ')
('time', 'NN')
('and', 'CC')
(GPE Eastern/JJ)
(GPE European/JJ)
('Summer', 'NN')
('Time', 'NNP')
('(', '(')
(ORGANIZATION EEST/NNP)
(')', ')')
('in', 'IN')
('the', 'DT')
('summer', 'NN')
('as', 'IN')
('daylight', 'NN')
('saving', 'VBG')
('time', 'NN')
('.', '.')
(ORGANIZATION EET/NNP)
('is', 'VBZ')
('two', 'CD')
('hours', 'NNS')
('ahead', 'RB')
('of', 'IN')
(ORGANIZATION Coordinated/NNP Universal/NNP Time/NNP)
('and', 'CC')
(ORGANIZATION EEST/NNP)
('is', 'VBZ')
('three', 'CD')
('hours', 'NNS')
('ahead', 'RB')
('.', '.')
(PERSON Finland/NNP)
('adopted', 'VBD')
(ORGANIZATION EET/NNP)
('in', 'IN')
('1921', 'CD')
(',', ',')
('and', 'CC')
('daylight', 'VBD')
('saving', 'VBG')
('time', 'NN')
('in', 'IN')
('its', 'PRP$')
('current', 'JJ')
('form', 'NN')
('from', 'IN')
('1981', 'CD')
('.', '.')
('Up', 'IN')
('to', 'TO')
('the', 'DT')
('19th', 'JJ')
('century', 'NN')
(',', ',')
('each', 'DT')
('locality', 'NN')
('used', 'VBN')
('its', 'PRP$')
('own', 'JJ')
('solar', 'JJ')
('time', 'NN')
(',', ',')
('which', 'WDT')
('could', 'MD')
('vary', 'VB')
('in', 'IN')
(GPE Finland/NNP)
('by', 'IN')
('up', 'IN')
('to', 'TO')
('31', 'CD')
('minutes', 'NNS')
('.', '.')
('In', 'IN')
('1862', 'CD')
(',', ',')
('a', 'DT')
('mean', 'JJ')
('time', 'NN')
('was', 'VBD')
('adopted', 'VBN')
('as', 'IN')
('a', 'DT')
('single', 'JJ')
('time', 'NN')
('zone', 'NN')
('for', 'IN')
('railway', 'NN')
('scheduling', 'NN')
('.', '.')
('Daylight', 'NNP')
('saving', 'VBG')
('time', 'NN')
('was', 'VBD')
('first', 'RB')
('attempted', 'VBN')
('in', 'IN')
('1942', 'CD')
(',', ',')
('abandoned', 'VBD')
('as', 'IN')
('not', 'RB')
('useful', 'JJ')
(',', ',')
('and', 'CC')
('introduced', 'VBD')
('again', 'RB')
('in', 'IN')
('1981', 'CD')
('to', 'TO')
('align', 'VB')
('with', 'IN')
('neighbouring', 'JJ')
('countries', 'NNS')
('.', '.')
('In', 'IN')
('2017', 'CD')
(',', ',')
('the', 'DT')
(GPE Finnish/NNP)
('parliament', 'NN')
('voted', 'VBD')
('to', 'TO')
('call', 'VB')
('on', 'IN')
('the', 'DT')
(ORGANIZATION European/NNP Union/NNP)
('to', 'TO')
('abolish', 'VB')
('daylight', 'NN')
('saving', 'VBG')
('time', 'NN')
('.', '.')
(PERSON Finland/NNP)
("'s", 'POS')
('time', 'NN')
('zone', 'NN')
('is', 'VBZ')
('maintained', 'VBN')
('by', 'IN')
('the', 'DT')
(ORGANIZATION VTT/NNP Technical/NNP)
('Research', 'NNP')
('Centre', 'NNP')
('of', 'IN')
(GPE Finland/NNP)
('and', 'CC')
('the', 'DT')
(ORGANIZATION Centre/NNP)
('for', 'IN')
(ORGANIZATION Metrology/NNP)
('and', 'CC')
(GPE Accreditation/NNP)
(',', ',')
('using', 'VBG')
('an', 'DT')
('atomic', 'JJ')
('clock', 'NN')
('and', 'CC')
('hydrogen', 'NN')
('monitors', 'NNS')
('.', '.')
('The', 'DT')
('24-hour', 'JJ')
('clock', 'NN')
('notation', 'NN')
('is', 'VBZ')
('used', 'VBN')
('in', 'IN')
(GPE Finland/NNP)
('.', '.')
